export const REQUEST_PROCESSING_STATUS = {
  INITIATED: 'SANDBOX_INITIATED',
  DELETED: 'SANDBOX_DELETED',
  PROVISIONED: 'SANDBOX_PROVISIONED',
  NEW: 'NEW',
  RENEW: 'RENEW',
  DELETE: 'DELETE',
  COMPLETED: 'COMPLETED',
};
export const STATUS = {
  REQUESTED: 'REQUESTED',
  FAILED: 'FAILED',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
};
